import type { Report, ReportStatus, StatusEvent } from "./types";

const makeDemoPhoto = (label: string, start = "#0A84FF", end = "#6EA8FF"): string =>
  `data:image/svg+xml;utf8,${encodeURIComponent(`
    <svg xmlns="http://www.w3.org/2000/svg" width="1200" height="900" viewBox="0 0 1200 900">
      <defs>
        <linearGradient id="bg" x1="0" x2="1" y1="0" y2="1">
          <stop stop-color="${start}" offset="0%" />
          <stop stop-color="${end}" offset="100%" />
        </linearGradient>
      </defs>
      <rect width="1200" height="900" fill="url(#bg)" rx="36" />
      <rect x="90" y="90" width="1020" height="720" fill="rgba(255,255,255,0.16)" rx="28" />
      <text x="600" y="410" fill="white" font-size="72" font-family="Inter, Arial, sans-serif" text-anchor="middle" font-weight="700">${label}</text>
      <text x="600" y="490" fill="rgba(255,255,255,0.82)" font-size="28" font-family="Inter, Arial, sans-serif" text-anchor="middle">Bantay Kalsada demo evidence</text>
    </svg>
  `)}`;

const makeEvent = (id: string, status: ReportStatus, atLabel: string, note: string): StatusEvent => ({
  id,
  status,
  atLabel,
  note,
});

// Seeded reports used for local-first and demo flows.
export const DEMO_REPORTS: Report[] = [
  {
    id: "demo-1",
    title: "Deep pothole on Katipunan Ave",
    description: "Large pothole near the corner of Katipunan and Aurora Blvd. Already caused two motorcycle accidents this week.",
    category: "pothole",
    severity: "high",
    status: "in_progress",
    geo: { lat: 14.6359, lng: 121.0775 },
    geohash: "wdw4z",
    address: "Katipunan Ave cor. Aurora Blvd",
    barangay: "Loyola Heights",
    city: "Quezon City",
    agencyId: "demo-dpwh",
    agencyName: "DPWH NCR",
    reporterUid: "demo-user",
    anonymous: false,
    photoURLs: [makeDemoPhoto("Pothole", "#E76F00", "#F8B35D")],
    aiSummary: "Severe road surface failure approximately 80cm wide. Immediate repair recommended.",
    aiCategory: "pothole",
    aiSeverity: "high",
    confirmCount: 12,
    urgencyScore: 87,
    updatedLabel: "2h ago",
    statusEvents: [
      makeEvent("demo-1-submitted", "submitted", "3d ago", "Report received from the community."),
      makeEvent("demo-1-reviewed", "ai_reviewed", "3d ago", "Reviewed and categorized as a pothole hazard."),
      makeEvent("demo-1-routed", "routed", "2d ago", "Sent to DPWH NCR for field action."),
      makeEvent("demo-1-ack", "acknowledged", "1d ago", "DPWH NCR confirmed receipt of the case."),
      makeEvent("demo-1-progress", "in_progress", "2h ago", "Repair crew dispatched to the location."),
    ],
    confirmedBy: ["demo-user-2", "demo-user-3"],
  },
  {
    id: "demo-2",
    title: "Flooded underpass — España",
    description: "Knee-deep flooding under the España flyover after the morning rain. Vehicles unable to pass.",
    category: "flood",
    severity: "high",
    status: "acknowledged",
    geo: { lat: 14.6098, lng: 120.9919 },
    geohash: "wdw3y",
    address: "España Blvd Underpass",
    barangay: "Sampaloc",
    city: "Manila",
    agencyId: "demo-mmda",
    agencyName: "MMDA",
    reporterUid: "demo-user-2",
    anonymous: false,
    photoURLs: [makeDemoPhoto("Flooded Area", "#0A84FF", "#63B3FF")],
    aiSummary: "Flash flooding likely caused by clogged drainage. Requires pump deployment.",
    aiCategory: "flood",
    aiSeverity: "high",
    confirmCount: 28,
    urgencyScore: 94,
    updatedLabel: "45m ago",
    statusEvents: [
      makeEvent("demo-2-submitted", "submitted", "Today", "Report received from the community."),
      makeEvent("demo-2-reviewed", "ai_reviewed", "Today", "Reviewed as a flooding case."),
      makeEvent("demo-2-routed", "routed", "1h ago", "Sent to MMDA for field response."),
      makeEvent("demo-2-ack", "acknowledged", "45m ago", "MMDA acknowledged the report and is coordinating response."),
    ],
  },
  {
    id: "demo-3",
    title: "Open manhole on Ortigas Ave",
    description: "Manhole cover missing on the inner lane. Reflective cone placed by passerby but still hazardous at night.",
    category: "manhole",
    severity: "high",
    status: "routed",
    geo: { lat: 14.5866, lng: 121.0631 },
    geohash: "wdw4x",
    address: "Ortigas Ave near Greenmeadows",
    barangay: "Ugong Norte",
    city: "Quezon City",
    agencyId: "demo-mmda",
    agencyName: "MMDA",
    reporterUid: "demo-user-3",
    anonymous: true,
    photoURLs: [makeDemoPhoto("Open Manhole", "#DC2626", "#F97316")],
    aiSummary: "Open manhole on a major thoroughfare. High night-time risk.",
    aiCategory: "manhole",
    aiSeverity: "high",
    confirmCount: 6,
    urgencyScore: 91,
    updatedLabel: "5h ago",
    statusEvents: [
      makeEvent("demo-3-submitted", "submitted", "Yesterday", "Report received from the community."),
      makeEvent("demo-3-reviewed", "ai_reviewed", "Yesterday", "Reviewed and categorized as a critical road hazard."),
      makeEvent("demo-3-routed", "routed", "5h ago", "Sent to MMDA and local engineering office for response."),
    ],
  },
  {
    id: "demo-4",
    title: "Broken stop sign at intersection",
    description: "Stop sign knocked down, lying on sidewalk. Drivers no longer stopping at the corner.",
    category: "sign",
    severity: "moderate",
    status: "scheduled",
    geo: { lat: 14.5547, lng: 121.0244 },
    geohash: "wdw4q",
    address: "Makati Ave cor. Jupiter St",
    barangay: "Bel-Air",
    city: "Makati",
    agencyId: "demo-mmda",
    agencyName: "MMDA",
    reporterUid: "demo-user",
    anonymous: false,
    photoURLs: [makeDemoPhoto("Broken Sign", "#7C3AED", "#A78BFA")],
    aiSummary: "Damaged regulatory signage. Replacement scheduled.",
    aiCategory: "sign",
    aiSeverity: "moderate",
    confirmCount: 3,
    urgencyScore: 62,
    updatedLabel: "Today",
    statusEvents: [
      makeEvent("demo-4-submitted", "submitted", "2d ago", "Report received from the community."),
      makeEvent("demo-4-reviewed", "ai_reviewed", "2d ago", "Reviewed as damaged road signage."),
      makeEvent("demo-4-routed", "routed", "1d ago", "Sent to MMDA for replacement scheduling."),
      makeEvent("demo-4-scheduled", "scheduled", "Today", "Replacement work has been scheduled."),
    ],
  },
  {
    id: "demo-5",
    title: "Damaged drainage cover",
    description: "Drainage grate cracked and shifted. Pedestrians have to step around it.",
    category: "drainage",
    severity: "moderate",
    status: "ai_reviewed",
    geo: { lat: 14.5176, lng: 121.0509 },
    geohash: "wdw4j",
    address: "C5 Service Rd, Taguig",
    barangay: "Western Bicutan",
    city: "Taguig",
    reporterUid: "demo-user",
    anonymous: false,
    photoURLs: [makeDemoPhoto("Drainage Issue", "#7C3AED", "#D8B4FE")],
    aiSummary: "Cracked storm drain grate, pedestrian hazard.",
    aiCategory: "drainage",
    aiSeverity: "moderate",
    confirmCount: 1,
    urgencyScore: 55,
    updatedLabel: "Today",
    statusEvents: [
      makeEvent("demo-5-submitted", "submitted", "Today", "Report received from the community."),
      makeEvent("demo-5-reviewed", "ai_reviewed", "Today", "Reviewed and waiting to be routed."),
    ],
  },
  {
    id: "demo-6",
    title: "Tree branch blocking lane",
    description: "Fallen acacia branch blocking the rightmost southbound lane after last night's storm.",
    category: "obstruction",
    severity: "moderate",
    status: "submitted",
    geo: { lat: 14.676, lng: 121.0437 },
    geohash: "wdw5b",
    address: "Mindanao Ave",
    barangay: "Pasong Tamo",
    city: "Quezon City",
    reporterUid: "demo-user-2",
    anonymous: false,
    photoURLs: [makeDemoPhoto("Road Obstruction", "#4B5563", "#9CA3AF")],
    confirmCount: 0,
    urgencyScore: 48,
    updatedLabel: "Just now",
    statusEvents: [makeEvent("demo-6-submitted", "submitted", "Just now", "Report received from the community.")],
  },
  {
    id: "demo-7",
    title: "Faded crosswalk paint",
    description: "Pedestrian crossing markings nearly invisible at night. Near a school zone.",
    category: "other",
    severity: "low",
    status: "resolved",
    geo: { lat: 14.6042, lng: 121.0226 },
    geohash: "wdw3z",
    address: "Tomas Morato Ave",
    barangay: "Sacred Heart",
    city: "Quezon City",
    agencyId: "demo-dpwh",
    agencyName: "DPWH NCR",
    reporterUid: "demo-user-3",
    anonymous: false,
    photoURLs: [makeDemoPhoto("Crosswalk Before", "#6B7280", "#9CA3AF")],
    aiSummary: "Faded thermoplastic markings. Repainting completed.",
    aiCategory: "other",
    aiSeverity: "low",
    confirmCount: 4,
    urgencyScore: 30,
    updatedLabel: "3d ago",
    resolutionProof: {
      photoURL: makeDemoPhoto("Proof Uploaded", "#059669", "#34D399"),
      uploadedBy: "DPWH NCR",
      uploadedAtLabel: "3d ago",
    },
    statusEvents: [
      makeEvent("demo-7-submitted", "submitted", "6d ago", "Report received from the community."),
      makeEvent("demo-7-reviewed", "ai_reviewed", "6d ago", "Reviewed and categorized for repainting."),
      makeEvent("demo-7-routed", "routed", "5d ago", "Sent to DPWH NCR for field action."),
      makeEvent("demo-7-ack", "acknowledged", "4d ago", "DPWH NCR confirmed the case."),
      makeEvent("demo-7-resolved", "resolved", "3d ago", "Marked resolved with proof uploaded by DPWH NCR."),
    ],
  },
];

export const DEMO_NOTIFICATIONS = [
  {
    id: "n1",
    title: "Repair work started",
    body: "DPWH NCR has started work on the Katipunan pothole case.",
    reportId: "demo-1",
    at: "2h ago",
    unread: true,
  },
  {
    id: "n2",
    title: "More residents confirmed the issue",
    body: "12 nearby residents confirmed the Katipunan pothole report.",
    reportId: "demo-1",
    at: "5h ago",
    unread: true,
  },
  {
    id: "n3",
    title: "Report reviewed and routed",
    body: "The España flooding case was reviewed and routed to MMDA.",
    reportId: "demo-2",
    at: "Yesterday",
    unread: false,
  },
  {
    id: "n4",
    title: "Proof uploaded for a resolved issue",
    body: "DPWH NCR uploaded proof for the Tomas Morato crosswalk case.",
    reportId: "demo-7",
    at: "3d ago",
    unread: false,
  },
];

export const DEMO_INSIGHT = {
  area: "Quezon City",
  summary:
    "Three high-priority road hazards are still active nearby this week. Katipunan remains the most urgent corridor after dark.",
  trend: "up" as const,
};
