import type { Report } from "./types";

// Seeded demo reports — used when Firebase env vars aren't configured.
// Coordinates roughly around Quezon City / Manila for realism.
export const DEMO_REPORTS: Report[] = [
  {
    id: "demo-1",
    title: "Deep pothole on Katipunan Ave",
    description: "Large pothole near the corner of Katipunan and Aurora Blvd. Already caused two motorcycle accidents this week.",
    category: "pothole",
    severity: "high",
    status: "in_progress",
    geo: { lat: 14.6359, lng: 121.0775 },
    geohash: "wdw4z",
    address: "Katipunan Ave cor. Aurora Blvd",
    barangay: "Loyola Heights",
    city: "Quezon City",
    agencyId: "demo-dpwh",
    agencyName: "DPWH NCR",
    reporterUid: "demo-user",
    anonymous: false,
    photoURLs: [],
    aiSummary: "Severe road surface failure approximately 80cm wide. Immediate repair recommended.",
    aiCategory: "pothole",
    aiSeverity: "high",
    confirmCount: 12,
    urgencyScore: 87,
  },
  {
    id: "demo-2",
    title: "Flooded underpass — España",
    description: "Knee-deep flooding under the España flyover after the morning rain. Vehicles unable to pass.",
    category: "flood",
    severity: "high",
    status: "acknowledged",
    geo: { lat: 14.6098, lng: 120.9919 },
    geohash: "wdw3y",
    address: "España Blvd Underpass",
    barangay: "Sampaloc",
    city: "Manila",
    agencyId: "demo-mmda",
    agencyName: "MMDA",
    reporterUid: "demo-user-2",
    anonymous: false,
    photoURLs: [],
    aiSummary: "Flash flooding likely caused by clogged drainage. Requires pump deployment.",
    aiCategory: "flood",
    aiSeverity: "high",
    confirmCount: 28,
    urgencyScore: 94,
  },
  {
    id: "demo-3",
    title: "Open manhole on Ortigas Ave",
    description: "Manhole cover missing on the inner lane. Reflective cone placed by passerby but still hazardous at night.",
    category: "manhole",
    severity: "high",
    status: "routed",
    geo: { lat: 14.5866, lng: 121.0631 },
    geohash: "wdw4x",
    address: "Ortigas Ave near Greenmeadows",
    barangay: "Ugong Norte",
    city: "Quezon City",
    agencyId: "demo-mmda",
    agencyName: "MMDA",
    reporterUid: "demo-user-3",
    anonymous: true,
    photoURLs: [],
    aiSummary: "Open manhole on a major thoroughfare. High night-time risk.",
    aiCategory: "manhole",
    aiSeverity: "high",
    confirmCount: 6,
    urgencyScore: 91,
  },
  {
    id: "demo-4",
    title: "Broken stop sign at intersection",
    description: "Stop sign knocked down, lying on sidewalk. Drivers no longer stopping at the corner.",
    category: "sign",
    severity: "moderate",
    status: "scheduled",
    geo: { lat: 14.5547, lng: 121.0244 },
    geohash: "wdw4q",
    address: "Makati Ave cor. Jupiter St",
    barangay: "Bel-Air",
    city: "Makati",
    agencyId: "demo-mmda",
    agencyName: "MMDA",
    reporterUid: "demo-user",
    anonymous: false,
    photoURLs: [],
    aiSummary: "Damaged regulatory signage. Replacement scheduled.",
    aiCategory: "sign",
    aiSeverity: "moderate",
    confirmCount: 3,
    urgencyScore: 62,
  },
  {
    id: "demo-5",
    title: "Damaged drainage cover",
    description: "Drainage grate cracked and shifted. Pedestrians have to step around it.",
    category: "drainage",
    severity: "moderate",
    status: "ai_reviewed",
    geo: { lat: 14.5176, lng: 121.0509 },
    geohash: "wdw4j",
    address: "C5 Service Rd, Taguig",
    barangay: "Western Bicutan",
    city: "Taguig",
    reporterUid: "demo-user",
    anonymous: false,
    photoURLs: [],
    aiSummary: "Cracked storm drain grate, pedestrian hazard.",
    aiCategory: "drainage",
    aiSeverity: "moderate",
    confirmCount: 1,
    urgencyScore: 55,
  },
  {
    id: "demo-6",
    title: "Tree branch blocking lane",
    description: "Fallen acacia branch blocking the rightmost southbound lane after last night's storm.",
    category: "obstruction",
    severity: "moderate",
    status: "submitted",
    geo: { lat: 14.6760, lng: 121.0437 },
    geohash: "wdw5b",
    address: "Mindanao Ave",
    barangay: "Pasong Tamo",
    city: "Quezon City",
    reporterUid: "demo-user-2",
    anonymous: false,
    photoURLs: [],
    confirmCount: 0,
    urgencyScore: 48,
  },
  {
    id: "demo-7",
    title: "Faded crosswalk paint",
    description: "Pedestrian crossing markings nearly invisible at night. Near a school zone.",
    category: "other",
    severity: "low",
    status: "resolved",
    geo: { lat: 14.6042, lng: 121.0226 },
    geohash: "wdw3z",
    address: "Tomas Morato Ave",
    barangay: "Sacred Heart",
    city: "Quezon City",
    agencyId: "demo-dpwh",
    agencyName: "DPWH NCR",
    reporterUid: "demo-user-3",
    anonymous: false,
    photoURLs: [],
    aiSummary: "Faded thermoplastic markings. Repainting completed.",
    aiCategory: "other",
    aiSeverity: "low",
    confirmCount: 4,
    urgencyScore: 30,
  },
];

export const DEMO_NOTIFICATIONS = [
  { id: "n1", title: "Your report is now In Progress", body: "DPWH NCR crew dispatched to Katipunan Ave pothole.", reportId: "demo-1", at: "2h ago", unread: true },
  { id: "n2", title: "Community confirmed your report", body: "12 neighbors confirmed the Katipunan pothole.", reportId: "demo-1", at: "5h ago", unread: true },
  { id: "n3", title: "AI analysis complete", body: "Your España flooding report has been classified as High severity.", reportId: "demo-2", at: "Yesterday", unread: false },
  { id: "n4", title: "Report resolved", body: "Tomas Morato crosswalk has been repainted.", reportId: "demo-7", at: "3d ago", unread: false },
];

export const DEMO_INSIGHT = {
  area: "Quezon City",
  summary:
    "3 active high-severity reports near you this week. Pothole density up 18% along Katipunan corridor — drive cautiously after dark.",
  trend: "up" as const,
};